import type { NextPage } from "next";
import Head from "next/head";
import LastAirbender from "../components/LastAirbender";
import RickAndMorty from "../components/RickAndMorty";
import Tabs from "../components/Tabs";
import { useAppSelector } from "../redux/store";

const Home: NextPage = () => {
  const { category, isActive } = useAppSelector((store) => store.categories);
  return (
    <div className="flex flex-col items-center bg-blue-400 h-screen">
      <Head>
        <title>Fetch It!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Tabs />
      {!isActive && (
        <div className="mt-40">
          <h3 className="text-xl font-semibold">
            Please choose one of the options above to fetch some data.
          </h3>
        </div>
      )}

      <div className="w-full">
        {isActive && category && isActive === category[0] && <LastAirbender />}
        {isActive && category && isActive === category[1] && <RickAndMorty />}
      </div>
    </div>
  );
};

export default Home;
